### ISSUE TITLE
Your code looks good

### ISSUE THREAD

**Issue by n1rocket** [fabioCollini/ArchitectureComponentsDemo#2]
Hi, i'm learning AAC with your code, looks so great!

I can see that we can click in loop generating infinites activities.

Repo -> Author -> Repo -> Author ...

How could be better?

Search -> Repo -> Author and result to return to back?

Sorry my bad english, i only try to improve...

Thanks, see you

**Comment by fabioCollini** [comment]
Hi,
glad you like this project!
And you are right but the focus of this project is not on the ux/ui so I am trying to keep it simple.
